# Site settings
author: Aida Abdikulova
title: Aida Abdikulova's Blog
header-img: img/home-bg.png
email: abdikulova@gmail.com
copyright_name: Aida Abdikulova
description: > # this means to ignore newlines until "baseurl:"
  Blogging a journey to learn how to code.
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  aabdikul

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
